version: '3.3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_DATABASE=node_shopping
    volumes:
      - data:/db

volumes:
  data: